In [55]:
# import numpy
# create array x
import numpy as np
x = np.array([[1,2,3,4],[2,3,5,6]])

In [42]:
# print the shape of x
np.shape(x)

(2, 4)

In [12]:
# create a two dimensional array
x1 = np.matrix([[1,2,3],[2,3,4]])
print(x1)

[[1 2 3]
 [2 3 4]]


In [4]:
# print shape of 2d array

In [19]:
# reshape the array to 2 x 6
x2 = np.matrix([[1,2,3,4,5,6],[2,3,4,5,6,7]])
x3 = x2.reshape(2,6)
x3

matrix([[1, 2, 3, 4, 5, 6],
        [2, 3, 4, 5, 6, 7]])

In [21]:
# reshape the array to 1 x 12
x4 = x2.reshape(1,12)
x4

matrix([[1, 2, 3, 4, 5, 6, 2, 3, 4, 5, 6, 7]])

In [23]:
# transpose the array
x4 = x2.T
x4

matrix([[1, 2],
        [2, 3],
        [3, 4],
        [4, 5],
        [5, 6],
        [6, 7]])

In [46]:
# indexing method 1
x4[4,1]

6

In [34]:
# indexing method 2
x4[-2]

matrix([[5, 6]])

In [59]:
# indexing method 3
x4[:5,1]

matrix([[2],
        [3],
        [4],
        [5],
        [6]])

In [60]:
# indexing method 4
indexing = np.array([[2,3,14]])
x4(indexing)

TypeError: 'matrix' object is not callable

In [54]:
# indexing method 5
xy[0, xy[1] > 3]

NameError: name 'xy' is not defined

In [10]:
# indexing method 6

In [64]:
# create a function of a variance
import math
import numpy as np

p = np.array([2,4,6,8,10,12,1,2,3,5,6])

def variancefunct(array):
    s = sum(array) 
    c = len(array)
    avg = (float(s)/c)
    print(avg)
    x =0
    for i in p:
        x +=((i -avg)**2)
    var  = float(x)/len(array)
    return (var)
variancefunct(p)

5.36363636364


11.140495867768594

In [66]:
# create a function of a standard deviation # call a function inside another function
def stddeviation(array):
    return variancefunct(array)**.5
stddeviation(p)
print np.std(p)

5.36363636364
3.33773813649
